# ClusterIP for internal access (order service calls this)
# NodePort for external access (browser, curl)
apiVersion: v1
kind: Service
metadata:
  name: ecomm-product-service
  namespace: ecomm-dev
spec:
  selector:
    app: ecomm-product-service
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30001
  type: NodePort
